#!/usr/bin/env bash
# This Bash scriptcreates a file, diplays a setence indefinitely, displays a sentence when receiving a SIGTERM signal and SIGINt signal and deletes the file while terminating itself when receiving a SIGQUIT or SIGTERM signal.


function handle_sigterm
{
	echo "I hate the kill command"
	exit
}
function handle_sigint
{
	echo "Y U no love me?!"
	exit
}
function handle_sigquit
{
	rm /var/run/myscript.pid
	exit
}

trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done
