#!/usr/bin/env bash
# This Bash script displays the PID and process name of processes whose name contain "bash"

pids=$(pgrep -f bash)
for pid in $pids; do
	process_name=$(cat "/proc/$pid/cmdline" | tr '\0' ' ')
	echo "$pid, $process_name"
done
