#!/usr/bin/env bash
# This Bash script displays: "To infinity and beyond" indefinitely, witha sleep 2 between each iteration, "I am invinsible!!!" when receiving a SIGTERM signal.

function handle_sigterm
{
	echo "I am invincible!!!"
}
trap handle_sigterm SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
