#!/usr/bin/env bash
# This Bash script displays numbers from 1-100. FizzBuzz when the number is a multiple of 5 and 3, Fizz when the number is a multiple of 3 and Buzz whena multiple of 5. Otherwise diplay the number.

for ((num=1; num<=100; num++))
do
	if ((num % 3 == 0)) && ((num % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((num % 3 == 0 ))
	then
		echo "Fizz"
	elif ((num % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
