#!/usr/bin/env bash
# This Bash script that displays the time for 12 hours and 59 minutes: displays from 0 to 12, displays from 1 to 59.

hour=0
while [ $hour -le 12 ]
do
	echo "hour: $hour"
	minute=0
	while [ $minute -lt 60 ]
	do
		echo "$minute"
		minute=$((minute + 1))
	done
	hour=$((hour + 1))
done
