#!/usr/bin/env bash
# This Bash script displays: the content of the current directory in a list form and where the only part of the name after the first dash is displayed.

for file in *
do
	if [ -f "$file" ] && [ ! "${file:0:1}" = "." ]
	then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
